// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sellyourcar.Data;

#nullable disable

namespace sellyourcar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sellyourcar.Models.DatabaseViewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DatabaseViewModel");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Content = "devil is coming",
                            Created = new DateTime(2025, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "God with Blue Heart"
                        },
                        new
                        {
                            Id = 102,
                            Content = "Water raising",
                            Created = new DateTime(2025, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black skyies with lighting"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
